#-------------------------------
# General Site Settings

title: Wendy Aguilar//designer//coder
description: Thinker // Designer // Coder
email: agu.wnd@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About, url: '#about-me'}
- {name: CODE, url: '#code'}
- {name: DESIGN, url: '#design'}
- {name: ART, url: '#art'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Wendy specializes in making things** for human people.
  Most of the things he makes are [digital interfaces](http://travisneilson.com){:target="_blank"},
  but he also puts effort into crafting [next-level beats](http://soundcloud.com/travis-neilson){:target="_blank"}
  and [YouTube videos](http://youtube.com/user/devtipsfordesigners){:target="_blank"} about making codes happen.
skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '6'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '5'}
- {name: UX Design, value: '8'}
- {name: Programming, value: '6'}

#-------------------------------
# projects Section

design-projects:
- {name: The Take Off, folder: 'the-take-off', file: '/projects/the-take-off.html', color: '#110B2D', type: 'design'}
- {name: Agendi, folder: 'agendi', file: '/projects/agendi.html', color: '#E5E3E6', type: 'design'}
- {name: Codelily, folder: 'codelily', file: '/projects/codelily.html', color: '#373838', type: 'design'}
- {name: Hedron, folder: 'hedron-design', file: '/projects/hedron-design.html', color: '#D96B60', type: 'design'}
- {name: Spark Science, folder: 'spark-science', file: '/projects/spark-science.html', color: '#AC8E79', type: 'design'}

#-------------------------------
# projects Section

code-projects:
- {name: Hedron, folder: 'hedron-code', file: '/projects/hedron-code.html', color: '#CCDCDE', type: 'code'}
- {name: Dyno-Thumbs, folder: 'dyno-thumbs', file: '/projects/dyno-thumbs.html', color: '#CCDCDE', type: 'code'}
- {name: Color-Study, folder: 'color-study', file: '/projects/color-study.html', color: '#CCDCDE', type: 'code'}

#-------------------------------
# projects Section

hedron-projects:
- {name: The walk Home, folder: 'agendi', file: '/projects/proj-1.html'}
- {name: City-IN website concept, folder: 'agendi', file: '/projects/proj-2.html'}
- {name: Crispy Icons, folder: 'agendi', file: '/projects/proj-3.html'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/devtipsshow'}
- {icon: 'dribbble', link: 'https://dribbble.com/travisneilson'}
- {icon: 'behance', link: 'https://www.behance.net/travisneilson'}
- {icon: 'youtube', link: 'https://www.youtube.com/DevTipsForDesigners'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/travisneilson/'}


# social netprojects icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
